spring:
  application:
    name: codesync-api-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      match-trailing-slash: false
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          # CORS for API paths
          '[/api/**]':
            allowedOrigins:
              - http://localhost:5173
              - ${FRONTEND_URL:http://localhost:5173}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600



  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: INFO

    # Gateway core
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG

    # WebSocket routing
    org.springframework.web.reactive.socket: DEBUG
    org.springframework.web.reactive.socket.server: DEBUG
    org.springframework.web.reactive.socket.client: DEBUG

    # Reactor Netty (actual network layer)
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG

    # Your gateway code
    com.codesync.gateway: DEBUG



#    org.springframework.cloud.gateway: TRACE
#    com.codesync.gateway: DEBUG