server:
  port: 8081

spring:
  application:
    name: codesync-auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
    username: ${SPRING_DATASOURCE_USERNAME:postgres.uapqhpnndarzmcgtbiwv}
    password: ${SPRING_DATASOURCE_PASSWORD:DcdMIH3FmsnkMss3}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

github:
  client-id: ${GITHUB_CLIENT_ID:Ov23lijbHInilwhOf566}
  client-secret: ${GITHUB_CLIENT_SECRET:c5a8d43d633645be3fe28367fa4f19a0ccee8c6f}
  redirect-uri: ${GITHUB_REDIRECT_URI:http://localhost:8080/api/auth/github/callback}
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

